/**
 * The repo map's format — Step 59.
 *
 * `core` owns the vocabulary and the daemon builds the thing: building a map
 * reaches disk and a wasm parser, and `core` touches disk only through an
 * injected `HostEnv`. What lives here is the part every consumer has to agree
 * on byte for byte, because the rendered map sits inside a context file and
 * prompt caching is prefix-based.
 *
 * Pure, so the rules below are testable without a grammar.
 */
import { utf8Bytes as utf8Length } from "./brief.js";

/** What a symbol is, in the fewest characters a model will still read. */
export type RepoSymbolKind =
  | "fn"
  | "class"
  | "interface"
  | "type"
  | "enum"
  | "const"
  | "default"
  | "reexport";

export interface RepoSymbol {
  name: string;
  kind: RepoSymbolKind;
}

export interface RepoMapFile {
  /** Workspace-relative, posix. */
  path: string;
  /** Exported (or, for Python, public top-level) symbols, in source order. */
  symbols: RepoSymbol[];
}

export interface RenderedRepoMap {
  text: string;
  /** Files that did not fit under the byte cap, counted rather than named. */
  omitted: number;
}

/**
 * Render a map. **Byte-stable by construction**, which is the whole contract.
 *
 * - Files sort by directory, then name, by plain code-unit comparison — never
 *   `localeCompare` and never `readdir` order. The first moves with the system
 *   locale and the second with the filesystem, and either one reorders a line
 *   near the top and invalidates every cached token after it.
 * - **No line numbers.** They are content-derived, so they would be stable
 *   when nothing changed — but one inserted import shifts every symbol below
 *   it, and the map would churn on edits that changed nothing about the
 *   repository's shape. A path and a name are enough for any agent with a
 *   search tool.
 * - No timestamps, counts of anything time-dependent, or run ids.
 *
 * Grouped by directory, because the first version repeated the full path on
 * every line and spent a third of its bytes on `packages/core/src/`. Files
 * with nothing exported — tests, scripts — share one `also:` line per
 * directory: where they live is worth knowing, a line each is not.
 *
 * Over `maxBytes`, whole directories are dropped from the end of the sorted
 * order and the files in them counted. Dropping by size, as the brief budget
 * does, would make which directories survive depend on what happens to be
 * large this week; dropping from the end is stable as files are edited.
 */
export function renderRepoMap(
  files: readonly RepoMapFile[],
  maxBytes: number,
): RenderedRepoMap {
  const groups = new Map<string, RepoMapFile[]>();
  for (const file of files) {
    const dir = dirOf(file.path);
    const group = groups.get(dir) ?? [];
    group.push(file);
    groups.set(dir, group);
  }
  const dirs = [...groups.keys()].sort(byCodeUnit);

  const header =
    "## Repo map\n\n" +
    "Generated by Cuesheet from the workspace's source: each directory, its " +
    "files, and what each exports. Read it before listing or searching the tree.\n\n";
  let text = header;
  let bytes = utf8Length(header);
  let omitted = 0;
  let full = false;

  for (const dir of dirs) {
    const group = (groups.get(dir) ?? []).sort((a, b) =>
      byCodeUnit(a.path, b.path),
    );
    if (full) {
      omitted += group.length;
      continue;
    }
    const block = renderGroup(dir, group);
    const size = utf8Length(block);
    // Room is kept for the omission line, so adding it never overruns.
    if (bytes + size + OMISSION_RESERVE > maxBytes) {
      full = true;
      omitted += group.length;
      continue;
    }
    text += block;
    bytes += size;
  }

  if (omitted > 0) {
    text += `- …and ${String(omitted)} more file${omitted === 1 ? "" : "s"} not mapped (over the map's size cap)\n`;
  }
  return { text: text.trimEnd(), omitted };
}

const OMISSION_RESERVE = 96;

function byCodeUnit(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function dirOf(path: string): string {
  const slash = path.lastIndexOf("/");
  return slash === -1 ? "" : path.slice(0, slash + 1);
}

function renderGroup(dir: string, group: readonly RepoMapFile[]): string {
  const name = (file: RepoMapFile): string => file.path.slice(dir.length);
  const lines = [`- ${dir === "" ? "./" : dir}`];
  for (const file of group) {
    if (file.symbols.length > 0) {
      lines.push(`  - ${name(file)}: ${renderSymbols(file.symbols)}`);
    }
  }
  const bare = group.filter((file) => file.symbols.length === 0).map(name);
  if (bare.length > 0) lines.push(`  - also: ${bare.join(", ")}`);
  return `${lines.join("\n")}\n`;
}

const KIND_PREFIX: Record<RepoSymbolKind, string> = {
  fn: "fn ",
  class: "class ",
  interface: "interface ",
  type: "type ",
  enum: "enum ",
  const: "const ",
  default: "",
  reexport: "",
};

function renderSymbols(symbols: readonly RepoSymbol[]): string {
  return symbols
    .map((symbol) =>
      symbol.kind === "default"
        ? "default"
        : `${KIND_PREFIX[symbol.kind]}${symbol.name}`,
    )
    .join(", ");
}
