import { describe, expect, it } from "vitest";
import type { ContextAudit, ContextAuditFile } from "@cuesheet/core";
import { contextRows, summarizeContext, usd } from "./context.js";

function file(
  over: Partial<ContextAuditFile> & { id: string },
): ContextAuditFile {
  return {
    kind: "file",
    scope: "project",
    path: over.id.split(":")[1] ?? over.id,
    exists: true,
    bytes: 0,
    generatedBytes: 0,
    estimatedTokens: 0,
    generatedTokens: 0,
    loadedBy: [],
    perRunTokens: 0,
    ...over,
  };
}

function audit(over: Partial<ContextAudit> = {}): ContextAudit {
  return {
    perRun: { estimatedTokens: 12_400, usd: 0.0372, unpriced: [] },
    history: { runs: 3, estimatedTokens: 37_200, usd: 0.1116 },
    files: [],
    stations: [
      {
        stationId: "opus",
        harness: "claude-code",
        known: true,
        files: [],
        estimatedTokens: 12_400,
        runs: 3,
      },
    ],
    rates: [{ vendor: "anthropic", usdPerInputToken: 3e-6 }],
    ...over,
  };
}

describe("summarizeContext", () => {
  it("answers per run with a number, and calls it an estimate", () => {
    const summary = summarizeContext(audit());
    expect(summary.headline).toBe(
      "About 12.4k tokens of context per run across 1 Station (estimated).",
    );
    expect(summary.price).toBe(
      "About $0.037 a run at this project's observed price per input token (estimated).",
    );
    expect(summary.history).toContain("3 runs");
    expect(summary.history).toContain("$0.11");
  });

  it("says why there is no price instead of printing $0.00", () => {
    const summary = summarizeContext(
      audit({
        perRun: { estimatedTokens: 500, unpriced: ["opus"] },
        history: { runs: 0, estimatedTokens: 0 },
        rates: [],
      }),
    );
    expect(summary.price).toMatch(/^No price yet/);
    expect(summary.price).not.toContain("$");
    expect(summary.history).toBeNull();
  });

  it("names a Station it left out of the total", () => {
    const summary = summarizeContext(
      audit({
        perRun: { estimatedTokens: 900, usd: 0.5, unpriced: ["gpt", "qwen"] },
      }),
    );
    expect(summary.price).toContain("not counting gpt and qwen");
  });

  it("names a Station whose harness it cannot audit", () => {
    const summary = summarizeContext(
      audit({
        stations: [
          {
            stationId: "x",
            harness: "theirs",
            known: false,
            files: [],
            estimatedTokens: 0,
            runs: 0,
          },
        ],
      }),
    );
    expect(summary.unknown).toMatch(/^x uses a harness this build/);
  });
});

describe("contextRows", () => {
  it("multiplies, attributes, and hides declared files nobody wrote", () => {
    const rows = contextRows(
      audit({
        files: [
          file({
            id: "project:CLAUDE.md",
            estimatedTokens: 1_200,
            generatedTokens: 480,
            loadedBy: ["opus", "sonnet"],
            perRunTokens: 2_400,
          }),
          file({
            id: "user:.claude/CLAUDE.md",
            scope: "user",
            estimatedTokens: 50,
            loadedBy: ["opus"],
            perRunTokens: 50,
          }),
          file({ id: "project:MOCK.md", exists: false }),
        ],
      }),
    );
    expect(rows.map((r) => r.label)).toEqual([
      "CLAUDE.md",
      "~/.claude/CLAUDE.md",
    ]);
    expect(rows[0]).toMatchObject({
      size: "1.2k tokens",
      perRun: "×2 → 2.4k a run",
      loadedBy: "opus, sonnet",
      generated: "40% generated by Cuesheet",
    });
    expect(rows[1]?.generated).toBeNull();
  });

  it("does not round a small generated block down to 0%", () => {
    const rows = contextRows(
      audit({
        files: [
          file({
            id: "project:CLAUDE.md",
            estimatedTokens: 9_916,
            generatedTokens: 12,
            loadedBy: ["opus"],
          }),
        ],
      }),
    );
    expect(rows[0]?.generated).toBe("under 1% generated by Cuesheet");
  });
});

describe("usd", () => {
  it("never rounds a real cost down to nothing", () => {
    expect(usd(0.0004)).toBe("$0.00040");
    expect(usd(0)).toBe("$0");
    expect(usd(0.0372)).toBe("$0.037");
    expect(usd(1.234)).toBe("$1.23");
  });
});
