/**
 * What the context audit says, decided here rather than in the component —
 * Step 62.
 *
 * Same split as `ledger.ts` and `limits.ts`: vitest does not collect `.tsx`,
 * so a sentence that lives in a component is a sentence no test can reach.
 *
 * The rules worth guarding:
 *
 * - **"estimated" in the words, every time.** Tokens are bytes over four and
 *   dollars are those at this project's own observed rate. A bare number reads
 *   as a vendor's count, and somebody will quote it as one.
 * - **No price is a sentence, not `$0.00`.** A project that has never run
 *   cannot price anything, and a Station on a vendor that reports no dollars
 *   is left out of the total by name rather than silently.
 *
 * Type-only imports from `@cuesheet/core`, on purpose — see the note at the
 * top of `ledger.ts` about what a value import from the barrel does to the
 * browser bundle.
 */
import type {
  ContextAudit,
  ContextAuditFile,
  ContextAuditStation,
} from "@cuesheet/core";
import { compact } from "./ledger.js";

export interface ContextSummary {
  /** "About 12.4k tokens of context per run (estimated)". */
  headline: string;
  /** What that is in money, or why there is no money to say. */
  price: string;
  /** The same context over the runs already taken, or `null` before any. */
  history: string | null;
  /** Stations this build cannot audit, or `null`. */
  unknown: string | null;
}

export function summarizeContext(audit: ContextAudit): ContextSummary {
  const { perRun, history } = audit;
  const crew = audit.stations.length;
  const headline =
    crew === 0
      ? "No Stations, so no context is loaded yet."
      : perRun.estimatedTokens === 0
        ? `No always-loaded context across ${stationCount(crew)}.`
        : `About ${compact(perRun.estimatedTokens)} tokens of context per run across ${stationCount(crew)} (estimated).`;

  return {
    headline,
    price: priceLine(audit),
    history:
      history.runs === 0 || history.estimatedTokens === 0
        ? null
        : `At today's size, the ${String(history.runs)} run${history.runs === 1 ? "" : "s"} on the ledger would have loaded ${compact(history.estimatedTokens)} tokens of it` +
          (history.usd === undefined ? "." : ` — about ${usd(history.usd)}.`),
    unknown: unknownLine(audit.stations),
  };
}

function priceLine(audit: ContextAudit): string {
  const { perRun } = audit;
  if (perRun.estimatedTokens === 0) return "Nothing to pay for.";
  if (perRun.usd === undefined) {
    return audit.rates.length === 0
      ? "No price yet: nothing on this project has reported what it spent."
      : `No price for ${list(perRun.unpriced)}: ${perRun.unpriced.length === 1 ? "its vendor has" : "their vendors have"} not reported one on this project.`;
  }
  const missing =
    perRun.unpriced.length === 0
      ? ""
      : `, not counting ${list(perRun.unpriced)}, which ${perRun.unpriced.length === 1 ? "has" : "have"} no price`;
  return `About ${usd(perRun.usd)} a run at this project's observed price per input token${missing} (estimated).`;
}

function unknownLine(stations: readonly ContextAuditStation[]): string | null {
  const unknown = stations.filter((station) => !station.known);
  if (unknown.length === 0) return null;
  return `${list(unknown.map((s) => s.stationId))} ${unknown.length === 1 ? "uses a harness" : "use harnesses"} this build does not know, so ${unknown.length === 1 ? "its" : "their"} context cannot be counted.`;
}

export interface ContextRow {
  id: string;
  /** `CLAUDE.md`, `~/.claude/CLAUDE.md`, or the brief's label. */
  label: string;
  /** "1.2k tokens", or "not written yet". */
  size: string;
  /** "×2 → 2.4k a run", or "loaded by no Station". */
  perRun: string;
  /** "opus, sonnet". */
  loadedBy: string;
  /** "all generated by Cuesheet", "40% generated", or `null` for none. */
  generated: string | null;
  missing: boolean;
}

/** Only the sources somebody is paying for, or could be: missing ones last. */
export function contextRows(audit: ContextAudit): ContextRow[] {
  return audit.files
    .filter((file) => file.exists || file.loadedBy.length > 0)
    .map(row);
}

function row(file: ContextAuditFile): ContextRow {
  const by = file.loadedBy.length;
  return {
    id: file.id,
    label:
      file.kind === "brief"
        ? file.path
        : file.scope === "user"
          ? `~/${file.path}`
          : file.path,
    // A brief with no facts is empty, not unwritten: there is no file.
    size: file.exists
      ? `${compact(file.estimatedTokens)} tokens`
      : file.kind === "brief"
        ? "empty — no facts yet"
        : "not written yet",
    perRun:
      by === 0
        ? "loaded by no Station"
        : by === 1
          ? `${compact(file.perRunTokens)} a run`
          : `×${String(by)} → ${compact(file.perRunTokens)} a run`,
    loadedBy: file.loadedBy.join(", "),
    generated: generatedLine(file),
    missing: !file.exists,
  };
}

function generatedLine(file: ContextAuditFile): string | null {
  if (file.generatedTokens === 0 || file.estimatedTokens === 0) return null;
  if (file.generatedTokens >= file.estimatedTokens)
    return "all generated by Cuesheet";
  const share = Math.round((file.generatedTokens / file.estimatedTokens) * 100);
  // An empty block in a large hand-written file rounds to 0%, which reads as
  // "none" — and there is one, it is just small. Running the Desk found it.
  if (share === 0) return "under 1% generated by Cuesheet";
  return `${String(share)}% generated by Cuesheet`;
}

/**
 * Dollars at the precision the figure deserves. Context is often a fraction
 * of a cent a run; `$0.00` would say it is free, which is the claim this whole
 * step exists to stop anybody making.
 */
export function usd(value: number): string {
  if (value === 0) return "$0";
  // Two significant figures under a dime: 10k tokens is three cents at a
  // common price, and `$0.04` against `$0.03` hides most of what moved.
  if (value < 0.1) return `$${value.toPrecision(2)}`;
  return `$${value.toFixed(2)}`;
}

function stationCount(count: number): string {
  return `${String(count)} Station${count === 1 ? "" : "s"}`;
}

function list(items: readonly string[]): string {
  if (items.length <= 1) return items.join("");
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1] ?? ""}`;
}
