/**
 * Project the Commons into the context files each harness already reads.
 *
 * The store is global, but a projection is not. A fact with project ids goes
 * only to those projects; a fact with no project ids is the user-level crew
 * layer and is written once under the home directory. Keeping that split here
 * prevents whichever project happened to change last from leaking its memory
 * into every other run on the machine.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import nodePath from "node:path";
import type { Fact, HostEnv, ProjectRegistry } from "@cuesheet/core";
import type { ContextFile } from "@cuesheet/harness";
import type { CommonsStore } from "./commons.js";

export const PROJECTION_BEGIN = "<!-- cuesheet:begin -->";
export const PROJECTION_END = "<!-- cuesheet:end -->";

export interface CommonsProjectionOptions {
  store: CommonsStore;
  registry: ProjectRegistry;
  env: HostEnv;
  /** Read at regeneration time so a registry that gains a harness is current. */
  contextFiles: () => readonly ContextFile[];
}

export interface ProjectionReport {
  /** Absolute paths whose bytes changed. */
  written: string[];
  /** Absolute paths already containing the exact projection. */
  unchanged: string[];
}

export interface CommonsProjector {
  regenerate(): Promise<ProjectionReport>;
}

export class ProjectionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ProjectionError";
  }
}

/**
 * Build one serialized projection queue.
 *
 * A fact write and delete can arrive on adjacent HTTP requests. Without the
 * queue, the slower first render can finish after the second and put a deleted
 * fact back into every context file. The Commons store is the source of truth;
 * every queued turn re-reads it after the preceding turn finishes.
 */
export function createCommonsProjector(
  options: CommonsProjectionOptions,
): CommonsProjector {
  let chain: Promise<unknown> = Promise.resolve();

  return {
    regenerate() {
      const next = chain.then(run, run);
      chain = next.catch(() => undefined);
      return next;
    },
  };

  async function run(): Promise<ProjectionReport> {
    const facts = await options.store.list();
    const files = uniqueContextFiles(options.contextFiles());
    const projects = await options.registry.list();
    const written: string[] = [];
    const unchanged: string[] = [];

    const userFacts = facts.filter((fact) => fact.projects.length === 0);
    for (const file of files.filter(({ scope }) => scope === "user")) {
      await updateTarget(
        safeTarget(options.env.homedir, file.path),
        userFacts,
        written,
        unchanged,
      );
    }

    for (const project of projects) {
      // A missing project remains visible in the picker, but its old absolute
      // path is not a place the daemon should recreate just to write context.
      if (project.status !== "ok") continue;
      const projectFacts = facts.filter((fact) =>
        fact.projects.includes(project.id),
      );
      for (const file of files.filter(({ scope }) => scope === "project")) {
        await updateTarget(
          safeTarget(project.root, file.path),
          projectFacts,
          written,
          unchanged,
        );
      }
    }

    return { written, unchanged };
  }
}

/** The generated bytes are identical for every harness target in one scope. */
export function renderProjection(facts: readonly Fact[]): string {
  const body = [...facts]
    // Ids are ASCII by contract. A direct comparison is byte-stable across
    // machines; localeCompare can order the same strings differently under a
    // different system locale and defeat prompt caching for no content change.
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))
    .map(
      (fact) =>
        `## ${safeMarkdown(fact.title.trim())}\n\n${safeMarkdown(fact.body.trim())}`,
    )
    .join("\n\n");
  return `${PROJECTION_BEGIN}\n${body}${body === "" ? "" : "\n"}${PROJECTION_END}`;
}

/**
 * Replace only Cuesheet's block. Every byte outside it belongs to the operator.
 */
export function mergeProjection(existing: string, block: string): string {
  const begin = existing.indexOf(PROJECTION_BEGIN);
  const end = existing.indexOf(PROJECTION_END);
  const anotherBegin =
    begin === -1
      ? -1
      : existing.indexOf(PROJECTION_BEGIN, begin + PROJECTION_BEGIN.length);
  const anotherEnd =
    end === -1
      ? -1
      : existing.indexOf(PROJECTION_END, end + PROJECTION_END.length);

  if (
    (begin === -1) !== (end === -1) ||
    (begin !== -1 && end < begin) ||
    anotherBegin !== -1 ||
    anotherEnd !== -1
  ) {
    throw new ProjectionError(
      `Context file has an incomplete Cuesheet projection marker pair.`,
    );
  }
  if (begin !== -1) {
    const after = end + PROJECTION_END.length;
    return `${existing.slice(0, begin)}${block}${existing.slice(after)}`;
  }
  if (existing === "") return `${block}\n`;

  // Append rather than normalize. Trailing spaces and blank lines outside the
  // block may be deliberate Markdown and are not ours to rewrite.
  const separator = existing.endsWith("\n\n")
    ? ""
    : existing.endsWith("\n")
      ? "\n"
      : "\n\n";
  return `${existing}${separator}${block}\n`;
}

/** A fact may discuss the marker syntax without becoming marker syntax. */
function safeMarkdown(value: string): string {
  return value
    .replaceAll(PROJECTION_BEGIN, "&lt;!-- cuesheet:begin --&gt;")
    .replaceAll(PROJECTION_END, "&lt;!-- cuesheet:end --&gt;");
}

async function updateTarget(
  target: string,
  facts: readonly Fact[],
  written: string[],
  unchanged: string[],
): Promise<void> {
  const existing = await readText(target);
  // Do not create four empty context files on a fresh install. Once a block
  // exists, keep it current even when its last fact is removed.
  if (existing === null && facts.length === 0) return;

  const next = mergeProjection(existing ?? "", renderProjection(facts));
  if (next === existing) {
    unchanged.push(target);
    return;
  }
  await mkdir(nodePath.dirname(target), { recursive: true });
  await writeFile(target, next, "utf8");
  written.push(target);
}

async function readText(file: string): Promise<string | null> {
  try {
    return await readFile(file, "utf8");
  } catch (error) {
    if (
      typeof error === "object" &&
      error !== null &&
      "code" in error &&
      error.code === "ENOENT"
    ) {
      return null;
    }
    throw error;
  }
}

/** A third-party harness cannot turn a context path into an arbitrary write. */
function safeTarget(root: string, relative: string): string {
  if (nodePath.isAbsolute(relative)) {
    throw new ProjectionError(`Context path "${relative}" must be relative.`);
  }
  const target = nodePath.resolve(root, relative);
  const fromRoot = nodePath.relative(root, target);
  if (fromRoot === ".." || fromRoot.startsWith(`..${nodePath.sep}`)) {
    throw new ProjectionError(
      `Context path "${relative}" escapes its projection root.`,
    );
  }
  return target;
}

function uniqueContextFiles(
  files: readonly ContextFile[],
): readonly ContextFile[] {
  const seen = new Set<string>();
  return files.filter((file) => {
    const key = `${file.scope}\u0000${file.path}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
